### PR TITLE
Modulesync 0.7.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
does anybody have an idea about the fails on puppet4?

**Comment by bastelfreak** [comment]
this looks pretty good now, thanks to @alexjfisher. Anybody for/against releasing a 1.0 of extlib?

CC: @igalic @nibalizer @jyaworski

**Comment by alexjfisher** [comment]
@bastelfreak Do you want to remove the release 1.0.0 commit so we can get the rest merged for now?

**Comment by bastelfreak** [comment]
@alexjfisher done

**Pull request merged**
