### PR TITLE
rename fact `puppet_config` to `puppet_settings`

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
Fixes https://github.com/voxpupuli/puppet-extlib/issues/148

**Comment by vchepkov** [comment]
Also, unrelated to the issue at hand, but why the fact is confined to Linux only? Seems universal to me

**Comment by alexjfisher** [comment]
Have we checked that `puppet_settings` isn't a fact provided by some other module?
Would it make any sense at all to 'namespace' facts??  (eg by putting them in a toplevel extlib structured fact)

**Comment by b4ldr** [comment]
`puppet_settings` is part of [stdlib](https://github.com/puppetlabs/puppetlabs-stdlib/blob/master/lib/facter/puppet_settings.rb).  @alexjfisher do you mean having something like

```
facts['extlib'] = {'puppet_settings' => {...}}
```

**Comment by vchepkov** [comment]
Darn, you are right, puppet_settings.rb is part of the stdlib, no such fact though
extlib_puppet_settings.rb ?

**Comment by alexjfisher** [comment]
Interesting. It’s not that stdlib has a `puppet_settings` fact, just that it has a `puppet_settings.rb` *file*??

**Comment by vchepkov** [comment]
correct, that would be a conflict too

**Comment by alexjfisher** [comment]
FWIW, simplib would have also clashed if we just renamed this fact. :(
https://github.com/simp/pupmod-simp-simplib/blob/master/lib/facter/simp_puppet_settings.rb#L8

The fact might actually be better than what we've got in extlib, but I can hardly recommend just including that module as then you'll maybe get a whole bunch of other facts and other collisions...

eg
https://github.com/theforeman/puppet-foreman/blob/9c1787ad19b2cae407b25958095ecbf78757a959/lib/facter/sssd.rb#L5
and
https://github.com/simp/pupmod-simp-simplib/blob/c2242361824a19af3b4b610cfd2fb73215c9b5a2/lib/facter/ipa.rb#L20

**Pull request closed without merging**
