### PR TITLE
Rename `puppet_config` fact to `extlib__puppet_agent_config`

### LINKED ISSUE #148: Module conflicts with puppetlabs/puppet_agent
fact puppet_config is already provided by puppetlabs/puppet_agent module and represents path to the configuration file itself. IMHO fact should be renamed to puppet_settings

https://github.com/puppetlabs/puppetlabs-puppet_agent/blob/master/lib/facter/settings.rb#L9-L13

### PR DESCRIPTION
**Pull request by alexjfisher**
The previous fact name clashed with a fact from
`puppetlabs\puppet_agent`.  This commit renames it to
`extlib__puppet_config` and also makes it available as a
structured `extlib` fact for facter 4 users.

Supersedes #152
Fixes #148

### CODE REVIEW

**Comment by vchepkov** [comment]
The name does not properly represent the fact's content. It returns 'server' components as well, right? Also not show why do you need double `__`. IMHO, it should be named `extlib_puppet_config`

**Comment by llowder** [comment]
The double underscore serves as a  identifier in and of itself - much like the `::` in puppet code, which conveys a different meaning from `foo:bar`.

I don't see the name as misleading, as unless I am missing something, these are all **agent** side settings, even though some of them give information pertaining to the server/master.

**Comment by vchepkov** [comment]
Hmm, unless I am missing something, how is master's localcacert or ssldir are relevant on the agent?

**Comment by alexjfisher** [comment]
> Hmm, unless I am missing something, how is master's localcacert or ssldir are relevant on the agent?

I was trying to address https://github.com/voxpupuli/puppet-extlib/pull/152#discussion_r376680876 but maybe it's actually now more confusing.

**Comment by alexjfisher** [comment]
> > Hmm, unless I am missing something, how is master's localcacert or ssldir are relevant on the agent?
> 
> I was trying to address [#152 (comment)](https://github.com/voxpupuli/puppet-extlib/pull/152#discussion_r376680876) but maybe it's actually now more confusing.

Updated.

**Comment by vchepkov** [comment]
👍

**Pull request merged**
