### PR TITLE
Update from voxpupuli modulesync_config

### PR DESCRIPTION
**Pull request by jyaworski**

### CODE REVIEW

**Comment by igalic** [comment]
@jyaworski what kind of input do you need here?

**Comment by jyaworski** [comment]
@igalic this will make ruby 1.8.7 incompatible. I wanted comments on whether or not we should do that.

**Comment by igalic** [comment]
imo: there's no need to do that
we shouldn't hazardously remove support for people who are stuck with very :hankey: software vendors, or os versions, or similar things that are beyond their control.
we want to give them tools into their hands that make them feel slightly more in control of those situations.

**Comment by mmoll** [comment]
This would effectively remove support for Puppet < 4 (PE aside) in RHEL 6 based platforms (which are probably still quite common and are claimed supported in metadata.json) and SLES 11 (not so common without PE, but I have also seen that on more than one system). It should also be noted that Ubuntu/precise does have Ruby 1.8 as default and the Ruby 1.9.3p0 that also came with it is allegedly broken for Puppet.

**Comment by jyaworski** [comment]
I reinstated 1.8.7. Merging.

**Pull request merged**
